const electionDirectory = [
    "PiliPinasDebates2022",
    "PipiPinas Debates 2022",
    "Halalan2022",
    "Halalan 2022",
    "VoteSafePilipinas",
    "Vote Safe Pilipinas",
    "PHVote",
    "PH Vote",
    "AnyareComelec",
    "Anyare Comelec",
    "Election2022PH",
    "Election 2022 PH",
    "PHElection2022",
    "PH Election 2022",
    "MahalinNatinAngPilipinas",
    "Mahalin Natin Ang Pilipinas",
    "BumotoKa",
    "Bumoto Ka",
    "Eleksyon2022",
    "Eleksyon 2022",
    "2022Eleksyon",
    "2022 Eleksyon",
    "WeDecide",
    "We Decide",
    "SMNIPresidentialDebate",
    "SMNI Presidential Debate",
    "LetLeniLead",
    "Let Leni Lead",
    "Kakampink",
    "Kakam pink",
    "AngatBuhayLahat",
    "Angat Buhay Lahat",
    "IpanloNa10To",
    "Ipanalo Na10 To",
    "Ipanalo Natin To",
    "Ipanalo Naten To",
    "KulayRosasAngBukas",
    "Kulay Rosas Ang Bukas",
    "KulyRosasAngBukas",
    "Kuly Rosas Ang Bukas",
    "LabanLeni2022",
    "Laban Leni 2022",
    "AgawBuhayLahat",
    "Agaw Buhay Lahat",
    "MarcosMagnanakaw",
    "Marcos Magnanakaw",
    "BBMIsMyPresident",
    "BBM Is My President",
    "BBMIsMyPresident2022",
    "BBM Is My President 2022",
    "MarcosDuwag",
    "Marcos Duwag",
    "PulaAngKulayNgRosas",
    "Pula Ang Kulay Ng Rosas",
    "PulaAngKulayNgMagnanakaw",
    "Pula Ang Kulay Ng Magnanakaw",
    "PulaAngKulayNgPosas",
    "Pula Ang Kulay Ng Posas",
    "BBMSARA2022",
    "BBM SARA 2022",
    "NeverAgain",
    "Never Again",
    "PanaloAngMahirap",
    "Panalo Ang Mahirap",
    "KayIskoPosible",
    "Kay Isko Posible",
    "PingGaling",
    "Ping Galing",
    "LacsonSotto2022",
    "Lacson Sotto 2022",
    "LacsonSottoTayo",
    "Lacson Sotto Tayo",
    "LeniRobredo",
    "Leni Robredo",
    "MariaLeonorRobredo",
    "Maria Leonor Robredo",
    "MariaLeonorGeronaRobredo",
    "Maria Leonor Gerona Robredo",
    "LeonorRobredo",
    "Leonor Robredo",
    "Leni",
    "Robredo",
    "Pinklawan",
    "Dilawan",
    "BongbongMarcos",
    "Bong Bong Marcos",
    "FerdinandMarcosJr",
    "Ferdinand Marcos Jr",
    "FerdinandMarcos",
    "Ferdinand Marcos",
    "FerdinandBongBongMarcos",
    "Ferdinand BongBong Marcos",
    "Bongbong",
    "Bong Bong",
    "Marcos",
    "BBM",
    "BabyM",
    "BobongMarcos",
    "Bobong Marcos",
    "Pulangaw",
    "ErnieAbella",
    "AbellaErnie",
    "Ernie",
    "Abella",
    "LeodyDeGuzman",
    "DeGuzmanLeody",
    "Leody",
    "de Guzman",
    "NorbertoGonzales",
    "GonzalesNorberto",
    "Norberto",
    "Gonzales",
    "MagondatoFaisal",
    "FaisalMagondato",
    "Magondato",
    "Faisal",
    "MontemayorJoseJr",
    "JoseJrMontemayor",
    "Montemayor",
    "Jose",
    "Jr.",
    "AtienzaLito",
    "LitoAtienza",
    "Atienza",
    "Lito",
    "WaldenBello",
    "BelloWalden",
    "Walden",
    "Bello",
    "DavidRosalito",
    "RosalitoDavid",
    "David",
    "Rizalito",
    "DuterteSara",
    "SaraDuterte",
    "Duterte",
    "Sara",
    "LopezManny",
    "MannyLopez",
    "Lopez",
    "Manny",
    "OngWillie",
    "DocWillieOng",
    "SD",
    "Ong",
    "Doc",
    "Willie",
    "PangilinanKiko",
    "KikoPangilinan",
    "Pangilinan",
    "Kiko",
    "SerapioCarlos",
    "CarlosSerapio",
    "Serapio",
    "Carlos",
    "SottoTitoVicente",
    "SottoVicenteTito",
    "SottoTito",
    "TitoSotto",
    "TitoVicenteSotto",
    "Sotto",
    "Vicente",
    "Tito",
    "MP2022",
    "MP 2022",
    "Lenikiko2022",
    "Leni Kiko 2022",
    "LetLeniLeave",
    "Let Leni Leave",
    "KayLeniTayo",
    "Kay Leni Tayo",
    "KayLeniTalo",
    "Kay Leni Talo",
    "KayLeniTaloSiMarcos",
    "Kay Leni Talo Si Marcos",
    "Kakampwet",
    "Kakam pwet",
    "Kakampuwet",
    "Kakam puwet",
    "LeniTangaSaLahat",
    "Leni Tanga Sa Lahat",
    "LenLenLoser",
    "LenLen Loser",
    "Len Len Loser",
    "AgawBuhayLahat",
    "Agaw Buhay Lahat",
    "BBMSaraUNITEAM",
    "BBM Sara UNITEAM",
    "UNITEAM",
    "LeniLiwanagSaDiliim",
    "Leni Liwanag Sa Dilim",
    "LeniLugaw",
    "Leni Lugaw",
    "KayLeniPatayTayo",
    "Kay Leni Patay Tayo",
    "NoToLeniKiko2022",
    "No To Leni Kiko 2022",
    "BBMParaSaLahat",
    "BBM Para Sa Lahat",
    "LENIDUWAG",
    "Leni Duwag",
    "PulaAngTaguig",
    "Pula Ang Taguig",
    "PHVoteResults",
    "PH Vote Results",
    "SwitchToIsko",
    "Switch To Isko",
    "BumotoKa",
    "Bumoto Ka",
    "Election2022PH",
    "Election 2022 PH",
    "NeverAgain",
    "Never Again",
    "WeDecide",
    "We Decide",
    "THE6832MAGIC",
    "The 6832 Magic",
];

export { electionDirectory };
